services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - ./:/workspace
      - node_modules:/workspace/node_modules
    command: npm run dev -- --hostname 0.0.0.0 --port 3000

volumes:
  node_modules:

